{
 "title": "Imixs-Cloud - Container Overview",
 "description": "System And Docker Monitoring Template",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(cadvisor_version_info,instance)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "dthms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"manager-001:9100\"}"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\", instance=~\"^($Instance).*\"}[5m]))"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (name) (irate(container_cpu_usage_seconds_total{image!=\"\",instance=\"$Instance\"}[1m])) * 100)",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}