apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Cluster
  externalIPs:
  # Add your cluster ip address here:
  - {YOUR_CLUSTER_IP}


